[[redirects]]
from = "https://pegghy.geode-solutions.netlify.com/*"
to = "https://pegghy.geode-solutions.com/:splat"
status = 301
force = true

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[build]
base = "app"
publish = "../dist"
ignore = "exit 0"

[functions]
directory = "../netlify/functions"

[context.production]
command = "cd .. && sed -i 's/\"0\\.0\\.0\"/\"latest\"/g' package.json && cat package.json && npm i && npm list && npm run generate"
[context.production.environment]
PROJECT = "/pegghy"
SITE_BRANCH = ""
SITE_URL = "https://pegghy.geode-solutions.com"

[context.branch-deploy]
command = "cd .. && sed -i 's/\"0\\.0\\.0\"/\"next\"/g' package.json && cat package.json && npm i && npm list && npm run generate"
[context.branch-deploy.environment]
PROJECT = "/pegghy"
SITE_BRANCH = "/test"
SITE_URL = "https://next.pegghy.geode-solutions.com"
